### ISSUE TITLE
Исправить бургер меню

### ISSUE THREAD

**Issue by nurlansapyzhan** [AttractorSchool/ESDP-AP-10-1#102]
### Для чего это нужно?

Бургер меню нужен для удобного просмотра меню страницы 

### План решения: 

Зайти в папку base.html
Реализовать бургер меню

### Критерии приёмки:

На всех страницах будет доступно бургер меню

### Планируемое время работы:
2 часа

### Фактически затраченное время:

**Comment by IvanAshikhin** [comment]
Соответствует критерию приемки
