### ISSUE TITLE
Правила командной оценки времени выполнения задач при составлении и назначении тикетов.

### ISSUE THREAD

**Issue by ValentinKim531** [AttractorSchool/ESDP-AP-10-1#11]
### Конечный результат: 

Разработаны и определены правила предварительной оценки времени выполнения тикета на основании командной оценки времени выполнения задачи с помощью чисел Фибаначи и использования скрам техники.

### План решения: 

прослушать запись/поднять заметки встречи с ментором, изучить материалы по теме в интернете.

### Мотивация: 

Для эффективного планирования тикетов и времени на их исполнения в зависимости от разработчика, его темпов и эффективности работы.

### Критерии приёмки:

Правила размещены на git wiki проекте и внедрены для использлования в команде.

### Планируемое время работы:
3 часа

### Фактически затраченное время:

**Comment by daniyarotegen** [comment]
3 часов было достаточно для составления статьи, плюс статьи о гит флоу

**Comment by nurlansapyzhan** [comment]
Проверил статьи. Устраивает критериям приемки.
