### ISSUE TITLE
CRUD для модели Review(Отзыв)

### ISSUE THREAD

**Issue by nurlansapyzhan** [AttractorSchool/ESDP-AP-10-1#111]
### Для чего это нужно?

Позволит взаимодействовать с приложением на создание, удаление, обновление, детальный просмотр через API.

### План решения: 

Войти в папку api
В  папке views, в файле reviews_api_view.py написать CRUD функции через создание классов ReviewsSimpleView, ReviewsApiView.
В файле [urls.py](http://urls.py/) указать путь при котором будут работать эти функции.

### Критерии приёмки:

Через postman можно создавать, удалять, обновлять и детально просматривать review(отзыв) пользователя.

### Планируемое время работы:
1 час

### Фактически затраченное время:

**Comment by ValentinKim531** [comment]
Фактически затраченное время: 1 час
