### ISSUE TITLE
Функции вывода страниц для crud операций новостей

### ISSUE THREAD

**Issue by nurlansapyzhan** [AttractorSchool/ESDP-AP-10-1#112]
### Для чего это нужно?
Для создания, обновления и удаления новостей через сервер

### Как это сделать?
Зайти в папку webapp 
Создать html файлы для crud новостей
Создать в папке views файл для вывода страниц с crud операциями новостей, с помощью django view
Указать url пути для этих страниц

### Дополнительные действия
добавить валидацию в [forms.py](http://forms.py/) на длину строки не менее 2 символов в названии и описании новости

### Критерии приема
Зайдя на сайт, смогу создать новости, обновить их данные и удалить.

### Планируемое затраченное время:
3 часа

**Comment by ValentinKim531** [comment]
Фактически затраченное время:
3 часа

**Comment by IvanAshikhin** [comment]
Соответствует критерию приемки
