### ISSUE TITLE
Функции вывода страниц для crud операций мероприятия

### ISSUE THREAD

**Issue by nurlansapyzhan** [AttractorSchool/ESDP-AP-10-1#114]
### Для чего это нужно?
Для создания, обновления и удаления мероприятий через сервер

### Как это сделать?
Зайти в папку webapp 
Создать html файлы для crud мероприятий 
Создать в папке views файл для вывода страниц с crud операциями мероприятий, с помощью django view
Указать url пути для этих страниц

### Критерии приема
Зайдя на сайт, смогу создать мероприятие, обновить их данные и удалить.

### Планируемое затраченное время:
3 часа

### Фактически затраченное время:
3 часа

**Comment by AlibekBeket** [comment]
Всем критериям приема удовлетворяет
