### ISSUE TITLE
Создать функции вывода страниц для crud операций всех видов запросов

### ISSUE THREAD

**Issue by nurlansapyzhan** [AttractorSchool/ESDP-AP-10-1#117]
### Для чего это нужно?
Для создания, обновления и удаления запросов администратору

### Как это сделать?
Зайти в папку webapp
Создать html файлы для crud запросов
Создать формы для запросов
Создать в папке views файл для вывода страниц с crud операциями запросов, с помощью django view
Указать url пути для этих страниц

### Дополнительные действия:
Обновить фикстуры

### Критерии приемки
Зайдя на сайт, смогу создать запрос всех 3 типов, просмотреть, в зависимости от типа запроса, список запросов, обновить их данные и удалить.

### Планируемое затраченное время:
8 часа

### Фактически затраченное время:

**Comment by AlibekBeket** [comment]
Затраченное время:
20 часов
Пришлось дорабатывать формы и писать логику для создания запроса и для сортировки в зависимости от типа запроса, пользователя отправителя и утвержден ли этот запрос или нет, написал функцию для брони оплативших пользователей пользователей, написал функцию для ответа пользователя на запрос
