### ISSUE TITLE
Создание функционального макета (mockup) сайта проекта

### ISSUE THREAD

**Issue by ValentinKim531** [AttractorSchool/ESDP-AP-10-1#12]
### Конечный результат: 

Разработан фукнкциональный макет сайта проекта для демонтрации Заказчику основных функций и представлений сайта.

### План решения: 

Создать функцилнальный макет сайта с основными страницами и навигацией, на основе 
 Bootstrap HTML.

### Мотивация: 

Mockup (графическая схема страниц и их элементов) моможет Заказчику и участникам проекта понять как будет выглядеть проект в будущем визуально, определить его недостатки и достоинства.

### Критерии приёмки:

Функциональный макет сайта  реализован и продемонтстрирован Заказчику и участникам проекта.

### Планируемое время работы:
8 часов

### Фактически затраченное время:
10 часов 20 минут

**Comment by ValentinKim531** [comment]
Спасибо исправлено.

**Comment by nurlansapyzhan** [comment]
Задача удовлетворяет критерии приемки.
