### ISSUE TITLE
Deploy приложения на сервере Attractor School

### ISSUE THREAD

**Issue by IvanAshikhin** [AttractorSchool/ESDP-AP-10-1#121]
### Для чего это нужно?

Позволит запускать и тестировать (со стороны пользователя) приложение с любого устройства через браузер.

### План решения: 

 1. получение IP адреса для доступа к серверу Attractor School (получено)
 2. установка GIT на сервер, сопутствующих приложений (Docker, docker compose, nginx, postgresql)
 3. добавление доступа к серверу другим участникам команды (запросить SSH ключи у каждого)
 4. настройка приложения на сервере для возможности запуска 

p/s: пункты возможно будут дополнятся так как пока нет полного понимания по второй части задачи, в процессе изучения.

### Критерии приёмки:

приложение открывается с любого браузера

### Планируемое время работы:
7 часов

### Фактически затраченное время:

**Comment by ValentinKim531** [comment]
Фактически затраченное время: 7 часов


## 🧑‍💻Запуск приложения на сервере Attractor School

Запустить приложение (при условии, если оно находится в режиме запуска на сервере) в браузере:
```
http://138.68.78.122:9000
```

Чтобы зайти на сервер приложения для участников проекта (по которым добавлены SSH ключи в проект), 
необходимо набрать в терминале:

```
ssh root@138.68.78.122
```
Далее, чтобы оказаться в папке проекта, необходимо набрать `cd titany/ESDP-AP-10-1`
Дальнейшие действия (запуск/остановка приложения в Docker, миграции, редактирование кода, git push/pull и т.д.)
выполняются точно также как и на обычном локальном компьютере, но только через команды в терминале.
