### ISSUE TITLE
Создание функции интерактивного поиска на страничке Accounts приложения (список всех пользователей)

### ISSUE THREAD

**Issue by IvanAshikhin** [AttractorSchool/ESDP-AP-10-1#122]
### Для чего это нужно?

Позволит пользователю найти необходимый профиль других резидентов (по имени/фамилии)

### План решения: 

	1.	с помощью java script реализовать ajax поисковой запрос, разместить в файле /static/js/search.js
	2.	разместить окно поиска на странице Accounts (файл profile_list_django) 

### Критерии приёмки:

по первым буквам поиск находит и отображает совпадения в профилях в виде блоков (фамилия, имя, аватар), с возможностью детального просмотра профиля

### Планируемое время работы:
5 часов

### Фактически затраченное время:
12 часов (большая часть времени ушло на реализацию кода по адаптации стилей (в соответствие с уже реализованными стилями в templates) и извлечение фото профиля)

**Comment by ValentinKim531** [comment]
Фактически затраченное время:
12 часов (большая часть времени ушло на реализацию кода по адаптации стилей (в соответствие с уже реализованными стилями в templates) и извлечение фото профиля)

**Comment by AlibekBeket** [comment]
Всем требованиям задачи удовлетворяет
