### ISSUE TITLE
Создать функцию и модель регистрации на мероприятие

### ISSUE THREAD

**Issue by IvanAshikhin** [AttractorSchool/ESDP-AP-10-1#127]
### Для чего это нужно?
Для возможности регистрироваться на мероприятие и просматривать кто зарегистрировался

### Как это сделать?
Зайти в папку webapp 

Создать модель для регистрации в файле models.py с такими полями как:
Пользователь [int] PK
Мероприятие [int] PK
Дата брони [date]
Дата оплаты [date]
Дата отмены брони [date]

Создать в папке views файл для регистрации на мероприятие, с помощью django view
Указать url путь для этой функции

### Критерии приема
При детальном просмотре мероприятия, чтобы мог регистрироваться 

### Планируемое затраченное время:
5 часа

### Фактически затраченное время:
10 часов

**Comment by AlibekAlikhan** [comment]
10 часов, исправлял баг логики

**Comment by AlibekBeket** [comment]
Всем требованиям удовлетворяет
