### ISSUE TITLE
Cоздание функционала групповых чатов

### ISSUE THREAD

**Issue by IvanAshikhin** [AttractorSchool/ESDP-AP-10-1#129]
### Для чего это нужно?

Позволит создавать групповые чаты для пользователей, где они смогут общаться.

### План решения: 

 1. с помощью centrifugo создать групповые чаты.

### Критерии приёмки:

админ сможет создать групповые чаты, несколько пользователей смогут общаться внутри чата

### Планируемое время работы:
8 часов

### Фактически затраченное время:

**Comment by daniyarotegen** [comment]
Удовлетворяет критериям
