### ISSUE TITLE
Подготовка к демонтрации чата Заказчику

### ISSUE THREAD

**Issue by ValentinKim531** [AttractorSchool/ESDP-AP-10-1#13]
### Конечный результат: 

Разработан прототип чата, а также определены аналоги готовых решений сторонних разработчиков. На выбор Заказчику.

### План решения: 

- Доработать до приемлемого уровня с целью демонтрации Заказчику собственного прототипа чата.
- Определить подходящие аналоги чатов из готовых решений сторонних разработчиков (возможно на платной основе)

### Мотивация: 

Чат - основная фишка проекта, главный функционал сайта(приложения) для коммуникации между участниками клуба.

### Критерии приёмки:

Желаемый вариант (собственная разработка или сторонее решение) определен Заказчиком.

### Планируемое время работы:
8 часов

### Фактически затраченное время:

**Comment by AlibekBeket** [comment]
Сделал концепт чат для демонстрации: работает на http запросах(постоянно отправляет запрос на получение данных от сервера)
Чтоб скачать саму программу нужно:
1. зайти на [https://github.com/AlibekBeket/ESDP-AP-10-1-Check_functions/tree/alibek_beket](url), 
2. войте в папку 'task_13', 
3. в папке нужно создать виртуальное окружение 
4. сделать миграцию
5. создать суперюзера
6. запустить приложение и войти в админку и внутри создать пользователей
7. в html файле есть блок див с классом "user_id", в нем нужно менять id на pk пользователя который будет отправлять сообщение
8. при запуске приложения зайти на страницу и отправить сообщение(если вы поменяли id пользователя обновить сайт)

**Comment by AlibekBeket** [comment]
- На само создание чата ушло 3 часа 
- Изучение модели чата с способами решения ушло 3 часа
- На изучение веб-сокетов и django channels ушло 5 часов 
Общее время 11 часов

**Comment by nurlansapyzhan** [comment]
Удовлетворяет критериям приемки.
