### ISSUE TITLE
Исправить разметку для вывода фотографий мероприятия и пользователей

### ISSUE THREAD

**Issue by IvanAshikhin** [AttractorSchool/ESDP-AP-10-1#131]
### Для чего это нужно?

Позволит корректно отображать фотографии мероприятий и пользователей.

### План решения: 

Исправить HTML файлы в которых фигурируют фотографии мероприятий и пользователей 

### Критерии приёмки:

Корректно отображаются фотографии пользователей и мероприятий

### Планируемое время работы:
1 час

### Фактически затраченное время:
1 час

**Comment by nurlansapyzhan** [comment]
Фактически затраченное время 1 час
