### ISSUE TITLE
Осуществления функционала файлообмена в чате и внедрения эмоджи

### ISSUE THREAD

**Issue by IvanAshikhin** [AttractorSchool/ESDP-AP-10-1#135]
### Для чего это нужно?

Позволит пользователю прикреплять файлы для обмена ими в чате , так же добавление emoji в чат по просьбе заказчика.

### План решения: 

 1. Реализовать функционал добавление файлов.
 2. Реализовать функционал добавление emoji.

### Критерии приёмки:

Пользователь сможет прикреплять файлы внутри чата, так же пользователь сможет вставлять emoji внутри чата

### Планируемое время работы:
8 часов

### Фактически затраченное время:

**Comment by AlibekBeket** [comment]
Всем условиям задачи удовлетворяет

**Comment by daniyarotegen** [comment]
Фактически затраченное время: 10 часов, так как решал баг с дублирующимися сообщениями при отправке файлов и исправил вывод аватара пользователей для новых сообщений
