### ISSUE TITLE
Создание стилей для страниц "Чата"

### ISSUE THREAD

**Issue by IvanAshikhin** [AttractorSchool/ESDP-AP-10-1#138]
### Для чего это нужно?

Реализация стиля страниц 'Чата' в соответствии с утвержденным дизайном

### План решения: 

Добавить в файл style.css код

### Критерии приёмки:

Страница будет оформлена в соответствии с дизайном всего приложения

### Планируемое время работы:
4 часа

### Фактически затраченное время:
6 часов

**Comment by AlibekBeket** [comment]
Всем критериям приема удовлетворяет
