### ISSUE TITLE
Создать модель мероприятий

### ISSUE THREAD

**Issue by AlibekBeket** [AttractorSchool/ESDP-AP-10-1#14]
### Для чего это нужно?

Модель мероприятий позволяет нам хранить все данные о мероприятиях

### План решения: 

Войти в папку webapp

Создать в папке models файл cities.py
В нем создать модель Cities с полями:
* Наименование города

Создать в папке models файл type_events.py
В нем создать модель TypeEvents с полями:
* Наименование типа мероприятия

Создать в папке models файл events.py
В нем создать модель Events с полями:
* Наименование*
* Организатор* (pk) Один к одному
* Город* (pk) Один к одному
* Тип мероприятия* (pk) Один к одному
* Дата-время мероприятия*
* Количество мест*
* Дата-время начала регистрации
* Дата-время конца регистрации*
* Пользователи которые забронировали место (pk) Многие ко многим
* Пользователи которые оплатили (pk) Многие ко многим
* Описание*
* Место*
* Цена*
* Дата-время создания*
* Дата-время обновления*
* Фотография*
* Удален* (bool) defoult='false'

### Дополнительные действия:
Зарегистрировать все модели в админке
Создать функцию которая при удалении мероприятия превращает булевое значение поля 'Удален' в 'true'
Указать в файл __init__.py путь до всех созданных моделей
Создать 'фикстуры' в папке fixtures в виде 'json' файла

### Критерии приёмки:

Через админ панель я смогу создать города, тип мероприятия и само мероприятие 

### Планируемое время работы:
3 часов

### Фактически затраченное время:
3 часа 42 минуты

**Comment by AlibekAlikhan** [comment]
Причина долгой работы,  в настройке файла settings  
Время: 3 часа 42 минуты

**Comment by AlibekBeket** [comment]
Критерию приема удовлетворяет
