### ISSUE TITLE
Создание фикстур по всем моделям приложения (кроме чата) для запуска на сервере школы.

### ISSUE THREAD

**Issue by daniyarotegen** [AttractorSchool/ESDP-AP-10-1#146]
### Для чего это нужно?

Позволит произвести пользовательское тестирование, отладку, запуск первой “бета-версии”.

### План решения: 

 1. удалить имеющиеся фикстуры, обновить с git последнюю версию приложения
 2. создать фикстуры (не менее 5 шт.) для каждой модели (кроме чата) приложения и загрузить в файл dump_all.json

### Критерии приёмки:

фикстуры загружаются успешно и отображаются при запуске приложения.

### Планируемое время работы:
3 часа

### Фактически затраченное время:
3.5 часа

**Comment by ValentinKim531** [comment]
Фактически затраченное время: 3,5 часа
