### ISSUE TITLE
Переписать бэкенд и JS для календаря

### ISSUE THREAD

**Issue by daniyarotegen** [AttractorSchool/ESDP-AP-10-1#147]
### Для чего это нужно?

Переписать бэкенд и JS для календаря, чтобы улучшить его удобство использования.

### План решения: 

Произвести анализ текущего бэкенда и JS, затем разработать и реализовать улучшенную версию, и протестировать функционал.

### Критерии приёмки:

Новый бэкенд и JS успешно разработан, реализован и протестирован.

### Планируемое время работы:
4 часа

### Фактически затраченное время:
5 часов

**Comment by nurlansapyzhan** [comment]
Фактически затраченное время 5 часов. Дополнительное время ушло на вывод query параметров, реализацию фильтра с помощью query параметром и дополнительного функционала
