### ISSUE TITLE
Осуществить адаптивную верстку страница веб сайта

### ISSUE THREAD

**Issue by daniyarotegen** [AttractorSchool/ESDP-AP-10-1#148]
### Для чего это нужно?

Адаптивная верстка необходима для обеспечения корректного отображения и удобства использования страницы веб-сайта на различных устройствах с разными размерами экрана.

### План решения: 

Переписать фронтэнд с учетом адаптивности, то есть такой, который будет корректно отображаться на всех устройствах.

### Критерии приёмки:

Страница корректно отображается и удобно используется на различных устройствах с разными размерами экрана.

### Планируемое время работы:
4 часа

### Фактически затраченное время:
5 часов

**Comment by nurlansapyzhan** [comment]
Реализовать адаптивную верстку не получилось, так как это займет много времени. Фактически затраченное время 5 часов

**Comment by AlibekBeket** [comment]
Удовлетворяет всем критериям приема
