### ISSUE TITLE
Осуществление голосования через представления Django

### ISSUE THREAD

**Issue by daniyarotegen** [AttractorSchool/ESDP-AP-10-1#149]
### Для чего это нужно?

Реализация системы голосования через Django views позволит резидентам участвовать в голосованиях, что обеспечит интерактивность и возможность выражения мнения пользователями.

### План решения: 

Создать представления Django, которые позволят пользователям голосовать и просматривать результаты голосования.

### Критерии приёмки:

Пользователи могут без проблем голосовать и просматривать результаты голосования.

### Планируемое время работы:
6 часов

### Фактически затраченное время:

**Comment by AlibekAlikhan** [comment]
10 часов, не расчитал время
