### ISSUE TITLE
Создать модель новостей

### ISSUE THREAD

**Issue by AlibekBeket** [AttractorSchool/ESDP-AP-10-1#15]
### Для чего это нужно?

Модель новостей позволяет нам хранить все данные о новостях

### План решения: 

Войти в папку webapp

Создать в папке models файл news.py
В нем создать модель News с полями:
* Наименование*
* Пользователь который создал* (pk) Один к одному
* Город* (pk) Один к одному
* Описание*
* Фотографии Многие ко многим
* Дата-время создания*
* Дата-время обновления
* Удален* (bool) defoult='false'

### Дополнительные действия:
Зарегистрировать все модели в админке
Создать функцию которая при удалении новости превращает булевое значение поля 'Удален' в 'true'
Указать в файл __init__.py путь до модели новостей
Создать 'фикстуры' в папке fixtures в виде 'json' файла

### Критерии приёмки:

Через админ панель я смогу создать новость

### Планируемое время работы:

2 часов

### Фактически затраченное время:

3 часа

**Comment by ValentinKim531** [comment]
Фактически затраченное время:
3 часа (так как дополнительно потребовалось еще создать модель Image для всех изображений)

**Comment by AlibekBeket** [comment]
Критерии приема выполнены
