### ISSUE TITLE
Создание переменных окружения для совместимости запуска на сервере и на локальной машине

### ISSUE THREAD

**Issue by daniyarotegen** [AttractorSchool/ESDP-AP-10-1#151]
### Для чего это нужно?

Настройка переменных окружения необходима для того, чтобы обеспечить удобный переход между локальной и серверной средами без необходимости менять конфигурацию при каждом переключении.

### План решения: 

Настроить приложение таким образом, чтобы оно автоматически выбирало нужные параметры в зависимости от того, где оно запущено - на локальной машине или на сервере.

### Критерии приёмки:

- При запуске приложения на локальной машине оно автоматически использует адрес http://localhost:9000 или http://127.0.0.1:9000.
- При запуске приложения на сервере оно автоматически использует адрес http://138.68.78.122:9000.

### Планируемое время работы:
5 часов

### Фактически затраченное время:
4 часа

**Comment by daniyarotegen** [comment]
Фактически затраченное время: 4 часа вместе с тестированием на сервере

**Comment by AlibekBeket** [comment]
Критериям приема удовлетворяет
