### ISSUE TITLE
Создание тестов для моделей, связанных с функционалом общения в чате и пересылкой файлов

### ISSUE THREAD

**Issue by daniyarotegen** [AttractorSchool/ESDP-AP-10-1#153]
### Для чего это нужно?

Тестирование моделей, связанных с функционалом общения в чате и пересылкой файлов, обеспечит их стабильное и корректное функционирование, предотвращая потенциальные ошибки и уязвимости в системе общения.

### План решения: 

- Разработать набор базовых тестов для проверки моделей чата и передачи файлов.
- Провести тестирование, отслеживая возникающие ошибки и проблемы, и внося коррективы при необходимости.

### Критерии приёмки:

- Все тесты успешно проходят, подтверждая надёжное и корректное функционирование моделей чата и передачи файлов.
- Неверные или некорректные данные отвергаются этими моделями во время тестирования.

### Планируемое время работы:
4 часа

### Фактически затраченное время:

**Comment by AlibekBeket** [comment]
Всем критериям приема удовлетворяет

**Comment by daniyarotegen** [comment]
Фактически затраченное время: 5 часов с доработкой стилей чатрума
