### ISSUE TITLE
Тестирование календаря и детального просмотра мероприятия

### ISSUE THREAD

**Issue by daniyarotegen** [AttractorSchool/ESDP-AP-10-1#155]
### Для чего это нужно?

Тестирование календаря и детального просмотра мероприятия позволит обеспечить надежность и корректную работу данных функций. 

### План решения: 

- Разработать набор базовых тестов для проверки функциональности календаря и детального просмотра мероприятия
- Провести тестирование, отслеживая возникающие ошибки и корректируя их в ходе процесса

### Критерии приёмки:

- Все тесты успешно проходят, подтверждая стабильную и корректную работу календаря и детального просмотра мероприятия.
- Неверные или некорректные данные корректно обрабатываются и не приводят к сбоям.

### Планируемое время работы:
4 часа

### Фактически затраченное время:
4 часа

**Comment by nurlansapyzhan** [comment]
Фактически затраченное время 4 часа
