### ISSUE TITLE
Внедрение модели ролей в проект

### ISSUE THREAD

**Issue by daniyarotegen** [AttractorSchool/ESDP-AP-10-1#162]
### Для чего это нужно?

Для выдачи прав пользователям

### План решения: 

- Создать модель привилегий и объединить с моделью ролей
- Вписать в модель привилегий функционал
- Создать страницы для передачи прав пользователям

### Критерии приёмки:

- Весь созданный функционал работает корректно.

**Comment by AlibekBeket** [comment]
Затраченное время: 15 часов
Искал способы реализации динамических ролей, но большее время потратил на сому реализацию и внедрение всех функционалов для ролей(передачи роли пользователю и crud ролей)
