### ISSUE TITLE
Исправление фикстур пользователей модели Account.

### ISSUE THREAD

**Issue by daniyarotegen** [AttractorSchool/ESDP-AP-10-1#164]
### Для чего это нужно?

Позволит произвести пользовательское тестирование, отладку, запуск первой “бета-версии”.

### План решения: 

 1. удалить имеющиеся фикстуры пользователей
 2. зарегистрировать пользователей через страницу регистрации приложения
 3. наполнить данными профайлы пользователей 
 4. создать фикстуры для пользователей и загрузить в файл dump_all.json

### Критерии приёмки:

Фикстуры загружаются успешно и отображаются при запуске приложения, можно зайти под каждым пользователем в приложение.

### Планируемое время работы:
1 час

### Фактически затраченное время:

**Comment by ValentinKim531** [comment]
Фактически затраченное время: 1 час

**Comment by AlibekBeket** [comment]
Всем критериям приема удовлетворяет
