### ISSUE TITLE
Написание логики в функцию регистрации на мероприятие

### ISSUE THREAD

**Issue by daniyarotegen** [AttractorSchool/ESDP-AP-10-1#168]
### Для чего это нужно?
Для отображения кнопки регистрации в зависимости от дат начала, конца регистрации и если пользователь оплатил место

### Как это сделать?

- Добавить дополнительные булевые переменные на сервере в зависимости от даты начала мероприятия и дат начала и конца регистрации и в зависимости от количества мест и оплаченных мест,
- Создать дополнительную страницу для все пользователей которые зарегистрированны на мероприятие 

### Критерии приема?
В зависимости от всех факторов я смогу видеть или не видеть кнопки для регистрации

### Планируемое затраченное время: 
6 часов

**Comment by AlibekBeket** [comment]
Всем критериям приема удовлетворяет
