### ISSUE TITLE
Обновить размеры в css стилях

### ISSUE THREAD

**Issue by nurlansapyzhan** [AttractorSchool/ESDP-AP-10-1#169]
### Для чего это нужно?
Для корректного отображения на разных устройствах

### Как это сделать?

Переписать в css файле размеры приложения

### Критерии приема?
Корректное отображение на разных устройствах

### Планируемое затраченное время: 
1 час

### Фактически затраченное время:
1 час

**Comment by nurlansapyzhan** [comment]
Фактически затраченное время: 1 час

**Comment by AlibekBeket** [comment]
Всем критериям приема удовлетворяет
