### ISSUE TITLE
Создать функцию вывода списка новостей через api

### ISSUE THREAD

**Issue by AlibekBeket** [AttractorSchool/ESDP-AP-10-1#17]
### Для чего это нужно?

Позволяет нам получить список всех новостей со всей информацией

### План решения: 

Войти в папку api
В файле serializer.py указать в каком виде будет брать всю информацию из модели
В файле views.py написать саму функцию через класс
В файле urls.py указать путь при котором будет работать эта функция

### Дополнительные действия:

Обновить 'фикстуры' в папке fixtures в виде 'json' файла

### Критерии приёмки:

Через postman с get запросом можно вывести все мероприятия в виде json файла

### Планируемое время работы:
3 часов

### Фактически затраченное время:
2 часа

**Comment by ValentinKim531** [comment]
Фактически затраченное время:
2 часа (так как функция api только одна согласно тикета - просмотр списка новостей)

**Comment by AlibekBeket** [comment]
Всем критериям приема удовлетворяет
