### ISSUE TITLE
Создание тестов для EventsUpdateView, NewsUpdateView, NewsDeleteView, связанные с функционалом по редактированию мероприятий, новостей, удалению новостей.

### ISSUE THREAD

**Issue by daniyarotegen** [AttractorSchool/ESDP-AP-10-1#175]
### Для чего это нужно?

Тестирование функционалов EventsUpdateView, NewsUpdateView, связанных с функционалом по редактированию мероприятий, новостей обеспечит стабильное и корректное функционирование, предотвращая потенциальные ошибки и уязвимости в системе обновления данных мероприятий и новостей, удалению новостей

### План решения: 

- Разработать набор базовых тестов для проверки функционала редактирования мероприятия, новости, удаления новости
- Провести тестирование, отслеживая возникающие ошибки и проблемы, и внося коррективы при необходимости.

### Критерии приёмки:

- Все тесты успешно проходят, подтверждая надёжное и корректное функционирование редактирования мероприятия/новости, удаления новости.
- Неверные или некорректные данные отвергаются этими моделями во время тестирования.

### Планируемое время работы:
5 часов

### Фактически затраченное время:

8 часов (время вышезапларированного ушло на изучение материалов и исправление ошибок в коде тестирования)

**Comment by ValentinKim531** [comment]
Фактически затраченное время: 8 часов (время вышезапларированного ушло на изучение материалов и исправление ошибок в коде тестирования)
