### ISSUE TITLE
Расширение функционала отправки файловых сообщений

### ISSUE THREAD

**Issue by daniyarotegen** [AttractorSchool/ESDP-AP-10-1#182]
## Для чего это нужно?
Для улучшения user experience.

## Как это сделать?
Изучить наличие дополнительных функций и внедрить в чат. 

## Критерии приема?
Весь новый функционал работает без конфликтов. 

## Планируемое затраченное время:
8 часов

## Фактически затраченное время:

8 часов

**Comment by daniyarotegen** [comment]
Фактически затраченное врем - 8 часов

**Comment by ValentinKim531** [comment]
критериям приемки удовлетворяют
