### ISSUE TITLE
Доработка голосования через представления Django

### ISSUE THREAD

**Issue by AlibekAlikhan** [AttractorSchool/ESDP-AP-10-1#183]
### Для чего это нужно?

Чтобы видеть отчетность голосовалки для всех

### План решения: 

В детальном view голосования добавит context с вычеслением процентов голосования
### Критерии приёмки:

Пользователи могут без проблем голосовать и просматривать результаты голосования.

### Планируемое время работы:
1 час

### Фактически затраченное время:

**Comment by AlibekBeket** [comment]
Всем критериям приема удовлетворяет

**Comment by AlibekAlikhan** [comment]
Потратил 1 час времени
