### ISSUE TITLE
Замена стилей для страниц под мобильную версию

### ISSUE THREAD

**Issue by nurlansapyzhan** [AttractorSchool/ESDP-AP-10-1#187]
## Для чего это нужно?
Для корректного отображения страниц в мобильной версии

## Как это сделать?
Изменить css стили в приложении

## Критерии приема?
Корректно отображаются страницы в мобильной версии 

## Планируемое затраченное время:
4 часа

## Фактически затраченное время:
4 часа

**Comment by AlibekBeket** [comment]
Всем критериям приема удовлетворяет
