### ISSUE TITLE
Реализация непрерывной поставки на сервер приложения (при обновлении приложения в git)

### ISSUE THREAD

**Issue by ValentinKim531** [AttractorSchool/ESDP-AP-10-1#189]
### Для чего это нужно?

С целью автоматизации процесса поставки приложения на сервер школы (без ручного git pull) и бесперебойной работы

### План решения: 

создать и настроить .github/workflows/main.yml файл и произвести настройки переменных окружений базы, хоста, ssh ключа, авто-обновления с гита при изменениях.

### Критерии приёмки:

обновление на сервере школы происходит автоматически при обновлении файлов приложения на git

### Планируемое время работы:
4 часа

### Фактически затраченное время:
6 часов (потребовалось больше времени из за того, что реализовывал впервые и потратил много времени на эксперименты)

**Comment by daniyarotegen** [comment]
всем критериям удовлетворяет

**Comment by daniyarotegen** [comment]
всем критериям удовлетворяет
