### ISSUE TITLE
Нахождение opensourse проекты для чата

### ISSUE THREAD

**Issue by AlibekBeket** [AttractorSchool/ESDP-AP-10-1#20]
### Для чего это нужно?

Для реализации полноценного веб-мессенджера на сайте

### План решения: 

Поиск всех возможных opensourse решений для реализации чата
Прочтение документации
Вывод всех плюсов и минусов данного opensourse проекта
Объяснение остальным участникам проекта принцип работы выбранного opensourse веб-мессенджера

### Критерии приёмки:

Выбор одного единственного opensourse проекта для реализации веб-мессенджера

### Планируемое время работы:
13 часов

### Фактически затраченное время:

**Comment by IvanAshikhin** [comment]
Соответствует критериям приемки
