### ISSUE TITLE
Улутшение модели мероприятии 

### ISSUE THREAD

**Issue by AlibekAlikhan** [AttractorSchool/ESDP-AP-10-1#26]
### Для чего это нужно?

Для лучшего взаимодействия с моделью мероприятия

### План решения: 

Зайти в файл webapp/models/events.py и удалить поля бронированых и оплаченных пользователей и добавить допалнительное поле многое ко многим для брони и оплаты

### Критерии приёмки:

Проверить через админ понель и обновить фикстуры

### Допалнительное действие:

 Переписать админку и переделать сериалайзеры

### Планируемое время работы:
3 часов

### Фактически затраченное время:

**Comment by AlibekBeket** [comment]
Потратил 2 часа
