### ISSUE TITLE
Интеграция примера чата в проект

### ISSUE THREAD

**Issue by AlibekAlikhan** [AttractorSchool/ESDP-AP-10-1#27]
### Для чего это нужно?

Для реализации чата в пректе

### План решения: 

Нужно интегрировать в settings django channels и создать отдельный проект chat

### Критерии приёмки:

Отпрака сообщениий и принятие

### Планируемое время работы:
5 часов

### Фактически затраченное время:

**Comment by IvanAshikhin** [comment]
Задача не актуальна
