### ISSUE TITLE
Подготовить свод вопросов для встречи с Заказчиком

### ISSUE THREAD

**Issue by ValentinKim531** [AttractorSchool/ESDP-AP-10-1#3]
### Конечный результат: 

Сводный список вопросов в разрезе разделов собран со всех членов команды и приведен в единый список.

### План решения: 

Собрать со всех членов команды списки вопросов и составить общий свод в разрезе тем проекта на основе ТЗ.

### Мотивация: 

список вопросов необходим для уточнения и прояснения самой концепции проекта, так и деталей по реализации.

### Критерии приёмки:
Получены ответы на вопросы от Заказчика.

### Планируемое время работы:
2 часа

**Comment by nurlansapyzhan** [comment]
Потрачено 3,5 часа на выполнение так как, допольнительное время ушло на анализ списка фич и генерации новых вопросов.
