### ISSUE TITLE
Инициализировать rocket.chat на локальном устройстве

### ISSUE THREAD

**Issue by ValentinKim531** [AttractorSchool/ESDP-AP-10-1#33]
### Для чего это нужно?
Подключить чат на локальный сервер нужно для того, чтобы проверить полный функционал чата - rocket.chat и интеграции его с приложением.

### План решения:
Изучить документацию по установке на официальном сайте. Установить Docker и Docker Compose. Загрузить Compose файл с документации. Обновить образ Rocket.Chat Docker. Проверить работоспособность на локальном устройстве. 

### Дополнительные действия:
Изучить как работает Docker. 

### Критерии приемки:
Чат запускается на локальном устройстве и полностью функционирует. 

### Планируемое время работы:
5 часов

### Фактически затраченное время:
45 минут

**Comment by nurlansapyzhan** [comment]
Задача не актуальна. Причина: Rocket chat не удовлетворяет финансовым потребностям
