### ISSUE TITLE
Реализация "гамбургер-меню" веб-приложения с выпадающим списком и его стилизация

### ISSUE THREAD

**Issue by ValentinKim531** [AttractorSchool/ESDP-AP-10-1#34]
### Для чего нужно?
Для удобной навигации по web-приложению

### План решения
На базовой странице создать и разместить "гамбургер-меню" и стилизовать его

### Критерии приема 
Просмотр через любую страницу web-приложения "гамбургер-меню" с выпадающим списком

### Планируемое время
3 часа

### Фактически затраченное время

**Comment by AlibekBeket** [comment]
Потраченное время: 2 часа
