### ISSUE TITLE
Подготовить информацию о стоимости и преимуществах/недостатках платных решений для реализации чата

### ISSUE THREAD

**Issue by ValentinKim531** [AttractorSchool/ESDP-AP-10-1#35]
### Для чего это нужно?
Для того чтобы предоставить данные заказчику (визуально на маркерной доске показать преимущества и недостатки, а также цены различных платных решений сторонних чатов) для принятия решение и конечного выбора продукции для интеграции его в приложение.

### План решения:
Собрать информацию о ценах, которая есть в свободном доступе, где такой информации нет, заказать обратную связь и узнать о ценах. 

### Критерии приемки:
Визуально изложенная тезисно информация на маркерной доске для Заказчика, где указаны плюсы и минусы, цены для сравнения. Получить от Заказчика обратную связь (желательно - окончательное решение по выбору чата)

### Планируемое время работы:
5 часов

**Comment by IvanAshikhin** [comment]
Задача не актуальна
