### ISSUE TITLE
Создать модель отзывов и лайков

### ISSUE THREAD

**Issue by ValentinKim531** [AttractorSchool/ESDP-AP-10-1#37]
### Для чего это нужно?
Лайки: с помощью лайка пользователи (резиденты) выражают свое мнение о  другом пользователе (которому хотят этот лайк поставить), а получатели лайка — получают обратную связь в виде положительной отметки (лайка). Количество лайков помогает оценить, на сколько оцениваемый пользователь (резидент клуба) полезен, популярен или понравился за счет какого либо действия/поступка.

Отзывы: благодаря отзывам другие пользователи (резиденты клуба) смогут узнать об оцениваемом пользователе больше информации, служат социальным подтверждением, позволяют оценить уровень доверия к нему, на основе предоставленной в отзыве информации.

### План решения: 
Войти в папку accounts

Создать в папке models файл reviews.py

В reviews.py создать модель  Review с полями:
*  текст (str)
* создатель отзыва [int]
* профиль пользователя, к которому оставляется отзыв  [int]
* like (bool)
* дата создания [date]
* дата обновления [date]

### Дополнительные действия:
Произвести миграцию модели
Зарегистрировать модель в админке
Обновить 'фикстуры' в папке fixtures

### Критерии приёмки:
Через админ панель я смогу создать/удалить/отредактировать отзыв и лайк

### Планируемое время работы:
3 часа

**Comment by ValentinKim531** [comment]
Фактически затраченное время 3 часа

**Comment by AlibekBeket** [comment]
Всем критериям приема удовлетворяет
