### ISSUE TITLE
Добавление в wiki проекта - Правила работы с проектом

### ISSUE THREAD

**Issue by ValentinKim531** [AttractorSchool/ESDP-AP-10-1#4]
### Конечный результат: 

Список правил работы с проектом

### План решения: 

Обозначить список тем и описать в виде инструкции каждое правило работы с проектом.

### Мотивация: 

Информация необходима для успешного вовлечения  каждого члена команды в проект (для работы по единым правилам и методам).

### Критерии приёмки:
Раздел размещен и наполнен в wiki проекта.

### Планируемое время работы:
4 часа

**Comment by daniyarotegen** [comment]
Фактически затратил 5 часов на добавление статей так как разбирался в форматировании
