### ISSUE TITLE
Создать CRUD для модели мероприятия через API

### ISSUE THREAD

**Issue by IvanAshikhin** [AttractorSchool/ESDP-AP-10-1#44]
### Для чего это нужно?

Позволяет взаимодействовать с фунционалами такиме как: создание, удаление, обновление, детальный просмотр через API.

### План решения: 

Войти в папку api
В файле views.py написать CRUD функций.
В файле urls.py указать путь при котором будут работать эти функции.

### Критерии приёмки:

Через postman можно будет создавать, удалять, обновлять и детально просматривать

### Планируемое время работы:
2,5 часа

### Фактически затраченное время:

**Comment by AlibekAlikhan** [comment]
Было потрачено 2 часа

**Comment by IvanAshikhin** [comment]
Соответствует критерию приемки
