### ISSUE TITLE
Инициализировать centrifugo чат на локальном устройстве

### ISSUE THREAD

**Issue by IvanAshikhin** [AttractorSchool/ESDP-AP-10-1#45]
### Для чего это нужно?
Подключить чат на локальный сервер нужно для того, чтобы проверить полный функционал чата - centrifugo и интеграции его с приложением.

### План решения:
Изучить документацию по установке на официальном сайте. Установить Docker и Docker Compose. Загрузить файлы с официального репозитория. Запустить v.3 centrifugo python_django_chat_tutorial через команду 
docker compose up --build
. Проверить работоспособность на локальном устройстве. 

### Дополнительные действия:
Изучить как работает Docker и NGINX. 

### Критерии приемки:
Чат запускается на локальном устройстве и полностью функционирует. 

### Планируемое время работы:
5 часов

### Фактически затраченное время:

**Comment by nurlansapyzhan** [comment]
Фактически затраченное время 8 часов. Возникли проблемы с Docker и Nginx. После получились инициализировать чат через docker compose

**Comment by IvanAshikhin** [comment]
Фактически затраченное время 8 часов. Возникли проблемы с Docker и Nginx. После получились инициализировать чат через docker compose
