### ISSUE TITLE
Написать стили для всех действующих страниц

### ISSUE THREAD

**Issue by daniyarotegen** [AttractorSchool/ESDP-AP-10-1#51]
**Для чего это нужно?**
Написать стили для действующих страниц нужно для последующих демонстраций приложения заказчику

**План решения**
Создать файл _style.css_ и прописать стили для элементов. При надобности переделать html файл(дописать классы, изменить структуру).

**Критерии приемки**
Приложение функционирует с новым дизайном.

**Планируемое время работы**
5 часов

**Фактически затраченное время**
4,5 часа

**Comment by nurlansapyzhan** [comment]
Фактически затраченное время - 4,5 часов

**Comment by AlibekBeket** [comment]
Требованиям удовлетворяет
