### ISSUE TITLE
Перенос проекта на Docker с целью интеграции Centrifugo и Nginx

### ISSUE THREAD

**Issue by daniyarotegen** [AttractorSchool/ESDP-AP-10-1#52]
**Для чего это нужно?**
Для обеспечения гибкой и эффективной интеграции функционала чата в проекте, его необходимо перенести в Docker. Это позволит нам быстро и без проблем подключить такие инструменты, как Centrifugo и Nginx.

**План решения:**
- Создание Dockerfile для проекта.
- Создание файла docker-compose.yml, включающего все необходимые сервисы (база данных, Django, Centrifugo, Nginx).
- Тестирование и отладка всей системы.

**Критерии приёмки:**
- Dockerfile и docker-compose.yml файлы успешно созданы и конфигурированы.
- Все компоненты системы функционируют как ожидалось, приложение стабильно и без ошибок работает в Docker.

**Планируемое время работы:**
Ожидается, что данная задача займет примерно 8 часов, учитывая время на настройку Docker, создание и настройку конфигурационных файлов, а также тестирование и отладку системы.

**Фактическое время работы:**
Фактически затраченное время для настройки и отладки Docker файлов составила 3 часа, так как большая часть работы была проделана в самостоятельном проекте по изучению чата на Centrifugo.

**Comment by daniyarotegen** [comment]
Фактическое время работы:
Фактически затраченное время для настройки и отладки Docker файлов составила 3 часа, так как большая часть работы была проделана в самостоятельном проекте по изучению чата на Centrifugo.

**Comment by ValentinKim531** [comment]
Всем критериям задачи удовлетворяет.
