### ISSUE TITLE
Разработка и интеграция чата на Centrifugo в Django проект

### ISSUE THREAD

**Issue by daniyarotegen** [AttractorSchool/ESDP-AP-10-1#53]
**Для чего это нужно?**
Для осуществления функционала чата между пользователями нашего проекта, было решено разработать и интегрировать чат на базе Centrifugo. Цель состоит в том, чтобы связать модели пользователей проекта и реализовать функционал чата между ними.

**План решения:**

- Установка и настройка Centrifugo на сервере.
- Создание функций для обработки событий чата (получение, отправка сообщений).
- Интеграция моделей пользователей Django с Centrifugo (идентификация пользователей в чате).
- Разработка интерфейса чата (включая список активных пользователей, окно для ввода сообщения, область для отображения сообщений).
- Тестирование функционала чата.

**Критерии приёмки:**

- Centrifugo успешно установлен и настроен.
- Функции для обработки событий чата успешно созданы и корректно работают.
- Модели пользователей Django успешно интегрированы с Centrifugo, пользователи могут идентифицироваться в чате.
- Интерфейс чата корректно работает, пользователи могут отправлять и получать сообщения.
- Весь функционал чата успешно прошел тестирование и работает без ошибок.

**Планируемое время работы:**
Ожидается, что данная задача займет примерно 13 часов, учитывая время на настройку Centrifugo, разработку функций обработки событий чата, интеграцию с моделями пользователей Django, разработку интерфейса и тестирование.

**Фактическое время работы:**
3 часа (для интеграции уже имеющегося кода моделей и вью, остальной функционал, такой как интерфейс, в данный момент осуществить невозможно, так как отсутствует интерфейс функционала аутентификации)

**Comment by daniyarotegen** [comment]
**Фактическое время работы:**
Потребовалось 3 часа для создания моделей и вью, остальной функционал, такой как интерфейс, в данный момент осуществить невозможно, так как нужен функционал аутентификации. Проверить работоспособность чата можно через админ панель

**Comment by ValentinKim531** [comment]
критериям успешности задачи соответствует.
