### ISSUE TITLE
Добавление в wiki проекта - раздел О нас

### ISSUE THREAD

**Issue by ValentinKim531** [AttractorSchool/ESDP-AP-10-1#6]
### Конечный результат: 

Создан раздел, где можно ознакомиться со следующей информацией: Общая информация о команде и проекте, и ее участниках, цели и задачи команды.

### План решения: 

Сделать совместное фото команды, разработать список целей и задач в рамках проекта, сделать ссылки на личную страничку каждого учатсника.

### Мотивация: 

Страничка О нас нужна для того, чтобы любой посетитель раздела мог после прочтения данного раздела понять вкратце - о чем проект, участники проекта, суть проекта, цели и задачи.

### Критерии приёмки:
Раздел размещен и наполнен в wiki проекта.

### Планируемое время работы:
4 часа

**Comment by nurlansapyzhan** [comment]
Удовлетворяет критериям приемки.
