### ISSUE TITLE
Создание переменных окружения для настройки конфигурации проекта

### ISSUE THREAD

**Issue by daniyarotegen** [AttractorSchool/ESDP-AP-10-1#61]
**Описание:**
Для настройки конфигурационных параметров проекта, таких как база данных, секретные ключи, URL-адреса сторонних сервисов и другие параметры, необходимо создать и использовать переменные окружения. Это позволит гибко настраивать проект в различных средах и обеспечить безопасность конфиденциальных данных.

**План решения:**
1. Создать файл `.env` в корневой директории проекта.
2. В файле .env определить переменные окружения для настройки различных параметров проекта. Примеры переменных:

- **DATABASE_URL:** URL-адрес базы данных.
- **SECRET_KEY**: Секретный ключ проекта.
- **EMAIL_HOST**: Хост-адрес почтового сервера.
- **EMAIL_PORT:** Порт почтового сервера.
- **EXTERNAL_API_URL**: URL-адрес стороннего сервиса.

и другие необходимые переменные для конфигурации проекта.
3. В файле настроек Django (`settings.py`) добавить код для загрузки переменных окружения из файла `.env`. Используйте пакет `python-decouple` для этого. Пример кода:

```
python
Copy code
from decouple import config

DATABASES = {
    'default': config('DATABASE_URL')
}

SECRET_KEY = config('SECRET_KEY')

EMAIL_HOST = config('EMAIL_HOST')
EMAIL_PORT = config('EMAIL_PORT', cast=int)

EXTERNAL_API_URL = config('EXTERNAL_API_URL')
```

4. В коде проекта использовать эти переменные окружения для настройки соответствующих параметров, например, подключение к базе данных, настройки аутентификации, URL-адреса сторонних сервисов и т.д.
5. Добавить файл `.env` в файл `.gitignore`, чтобы исключить его из системы контроля версий Git и предотвратить попадание конфиденциальных данных в репозиторий.

**Критерии приемки:**
- Файл `.env` успешно создан и содержит необходимые переменные окружения для конфигурации проекта.
- Переменные окружения корректно загружаются из файла `.env` в настройках Django.
- Переменные окружения успешно использованы для настройки соответствующих параметров проекта.
- Проверено, что проект работает с правильной конфигурацией базы данных, секретными ключами, URL-адресами сторонних сервисов и другими параметрами.
- Файл `.env` добавлен в `.gitignore` для исключения из системы контроля версий Git.
- Тестирование функциональности проекта проведено и успешно пройдено.

**Планируемое время работы:**
Ожидается, что данная задача займет примерно 2 часа, включая создание `.env` файла, настройку переменных окружения, обновление настроек Django, проверку работоспособности конфигурации проекта и обновление `.gitignore`.

**Фактическое время работы:**
Фактически потратил 2 часа на установку библиотеки, и настройки файлов

**Comment by daniyarotegen** [comment]
Фактически потратил 2 часа на установку библиотеки, и настройки файлов

**Comment by ValentinKim531** [comment]
Задача критериям успешности соответствует.
