### ISSUE TITLE
Создать CRUD для модели новостей через API

### ISSUE THREAD

**Issue by daniyarotegen** [AttractorSchool/ESDP-AP-10-1#62]
### Для чего это нужно?

Позволяет взаимодействовать с фунционалом проекта, таким как: создание, удаление, обновление, детальный просмотр через API.

### План решения: 

- Войти в папку api
- В файле views.py написать CRUD функций.
- В файле urls.py указать путь при котором будут работать эти функции.

### Критерии приёмки:

Через postman можно будет создавать, удалять, обновлять и детально просматривать

### Планируемое время работы:
2,5 часа

### Фактически затраченное время:

**Comment by AlibekAlikhan** [comment]
Было потраче время на задачу 3 часа, больше времени затратил из-за использования докера
