### ISSUE TITLE
Создание Tasker и Road map проекта

### ISSUE THREAD

**Issue by ValentinKim531** [AttractorSchool/ESDP-AP-10-1#7]
### Конечный результат: 

Создан Tasker и RoadMap по проекту - обозначены основные разделы и этапы.

### План решения: 

Создать проект tasker и roadmap, подключить всех участников для возможности редактирования и заполнения.

### Мотивация: 

для контроля и мониторинга исполнения задач каждого члена команды.

### Критерии приёмки:
Раздел Tasker и Road map созданы и готовы к использованию.

### Планируемое время работы:
4 часа

**Comment by AlibekBeket** [comment]
Потратил 3 часа
Много времени не понадобилось, так как надо было просто подумать над удобством использования таблицы и родмапы для задач

**Comment by AlibekAlikhan** [comment]
Увидел вашу работу, всё хорошо
