### ISSUE TITLE
CRUD api для голосований

### ISSUE THREAD

**Issue by AlibekBeket** [AttractorSchool/ESDP-AP-10-1#74]
### Для чего это нужно?
Для реализации функционала голосования

### Как это сделать?
Войти в папку api
Написать сериализаторы для моделей голосований
В папке views написать crud функции
В urls.py написать пути для вывода этих функций

###  Критерии приема
Через постман я смогу создать новый список из голосований и увидеть его в админке

### Фактически затраченное время:
8 часов

**Comment by AlibekAlikhan** [comment]
Было потрачено времени: 8 часов

**Comment by AlibekBeket** [comment]
Удовлетворяет все требованиям
