### ISSUE TITLE
Разработка функционала регистрации и аутентификации с использованием JWT токенов и хранения через куки

### ISSUE THREAD

**Issue by AlibekBeket** [AttractorSchool/ESDP-AP-10-1#75]
### Для чего это нужно?
Необходимо разработать функционал регистрации и аутентификации используя JWT токены, которые будут храниться на клиентской стороне через куки.

### Как это сделать?
1. Реализовать функционал регистрации и аутентификации используя JWT токены
2. Реализовать механизм хранения JWT токенов через куки

### Критерии приема
 • Реализована генерация и проверка JWT токенов.
 • Реализован механизм хранения JWT токенов через куки.
 • Функционал протестирован и работает корректно.

### Планируемое затраченное время: 
8 часов.

**Comment by daniyarotegen** [comment]
Фактическое затраченное время: 8 часов

**Comment by AlibekBeket** [comment]
Удовлетворяет всем критериям приема
