### ISSUE TITLE
Создать CRUD для модели Account через API

### ISSUE THREAD

**Issue by ValentinKim531** [AttractorSchool/ESDP-AP-10-1#76]
### Для чего это нужно?

Позволяет взаимодействовать с фунционалами такиме как: создание, удаление, обновление, детальный просмотр через API.

### План решения: 

Войти в папку api
В  папке views, в файле pкofile.py написать CRUD функций через создание классов AccountsSimpleView, AccountApiView.
В файле urls.py указать путь при котором будут работать эти функции.

### Критерии приёмки:

Через postman можно будет создавать, удалять, обновлять и детально просматривать account пользователя.

### Планируемое время работы:
1,5 часа

### Фактически затраченное время:

**Comment by ValentinKim531** [comment]
Фактически затраченное время: 3 часа (ушлодоп время на поиск решения проблем с полями read only)

**Comment by AlibekBeket** [comment]
Всем критериям приема удовлетворяет
