### ISSUE TITLE
Настройка Centrifugo для авторизации через JWT токены и интергация чата

### ISSUE THREAD

**Issue by AlibekBeket** [AttractorSchool/ESDP-AP-10-1#78]
### Для чего это нужно?
Настройка Centrifugo для авторизации через JWT токены позволяет обеспечить безопасность и контроль доступа в чате.

### Как это сделать?
Настроить клиентскую библиотеку Centrifuge для использования JWT токенов.
Реализовать логику генерации и проверки JWT токенов.
Передать сгенерированный JWT токен для авторизации.

### Критерии приема:
Centrifugo настроен для авторизации через JWT токены.
JWT токен успешно передается при подключении к Centrifugo.
Приватные чаты между пользователями функционируют нормально. 

### Планируемое затраченное время: 
13 часов

**Comment by daniyarotegen** [comment]
Фактически затраченное время - 20 часов, дорабатывал систему авторизации на основе JWT токенов хранящихся в cookie, исправил механизм обновления access токенов при истечении используя refresh токен

**Comment by daniyarotegen** [comment]
Удовлетворяет критериям
