### ISSUE TITLE
Исправить ошибку в api_view мероприятии

### ISSUE THREAD

**Issue by AlibekAlikhan** [AttractorSchool/ESDP-AP-10-1#80]
### Для чего это нужно?

Позволит правильно создавать мероприятияI.

### План решения: 

Войти в папку api
В  папке views, в файле events_api.py исправить ошибку в post запросе 

### Критерии приёмки:

Через postman можно будет создавать мероприятия

### Планируемое время работы:
30 минут

### Фактически затраченное время:
30 минут

**Comment by AlibekAlikhan** [comment]
Затраченноое время: 30 минут

**Comment by AlibekBeket** [comment]
Критериям приема удовлетворяет
