### ISSUE TITLE
Исправить функции регистрации и аутентификации пользователя

### ISSUE THREAD

**Issue by AlibekBeket** [AttractorSchool/ESDP-AP-10-1#82]
### Для чего это нужно?
Для выдачи прав пользователю
### Как это сделать?
Написать js код для входа и регистрации пользователя
### Дополнительные действия
Сделать кнопку для выхода пользователя
### Критерии приема
Смогу зарегистрироваться и войти в этот новый аккаунт
### Планируемое затраченное время:
3 часов
### Фактически затраченное время:

5 часов  (так как пришлось дополнительно исправлять ссылки на страницу ленты новостей и создания функционала выхода из системы)

**Comment by daniyarotegen** [comment]
Фактически затраченное время - 5 часов, так как пришлось исправлять ссылки на ленту новостей

**Comment by daniyarotegen** [comment]
Фактически затраченное время + 3 часов из-за непредвиденных ошибок с хедерами на некоторых компьютерах
