### ISSUE TITLE
Создать функции вывода страниц для crud операций мероприятий

### ISSUE THREAD

**Issue by AlibekBeket** [AttractorSchool/ESDP-AP-10-1#84]
### Для чего это нужно?
Для создания, обновления и удаления мероприятий через сервер

### Как это сделать?
Зайти в папку webapp 
Создать html файлы для crud мероприятия
Создать в папку views файл для вывода страниц с crud операциями мероприятия
Написать js файлы для crud api
Указать url пути для этих страниц

### Дополнительные действия
Во всех api функциях указать пермишены

### Критерии приема
Зайдя на сайт, смогу создать мероприятие, обновить его данные и удалить его.

### Планируемое затраченное время:
5 часов

**Comment by daniyarotegen** [comment]
неактуально, так как для фронтенда будут использованы джанговские представления

**Comment by AlibekBeket** [comment]
Данная задача будет использоваться для демонстрации возможности использования api на сайте
Для этого мы объединим ветку с данной задачей с главной веткой
