### ISSUE TITLE
Создать функции вывода страниц для crud операций новостей

### ISSUE THREAD

**Issue by AlibekBeket** [AttractorSchool/ESDP-AP-10-1#85]
### Для чего это нужно?
Для создания, обновления и удаления новостей через сайт

### Как это сделать?
Зайти в папку webapp
Создать html файлы для crud новостей
Создать в папку views файл для вывода страниц с crud операциями новостей и прикрепить к ним html файлы
Написать js файлы для crud api новостей
Указать url пути для этих страниц

### Критерии приема
Зайдя на сайт, смогу создать новость, обновить его данные и удалить данную новость

### Планируемое затраченное время:
5 часов

**Comment by daniyarotegen** [comment]
неактуально, так как для фронтенда будут использованы джанговские представления

**Comment by AlibekBeket** [comment]
Данная задача будет использоваться для демонстрации возможности использования api на сайте
