### ISSUE TITLE
Создать функции вывода страниц для crud операций голосования

### ISSUE THREAD

**Issue by AlibekBeket** [AttractorSchool/ESDP-AP-10-1#86]
### Для чего это нужно?
Для создания, обновления и удаления списка голосования через сайт

### Как это сделать?
Зайти в папку webapp
Создать html файлы для crud голосования
Создать в папку views файл для вывода страниц с crud операциями голосования
Написать js файлы для crud api
Указать url пути для этих страниц

### Критерии приема
Зайдя на сайт, смогу создать список из голосований, обновить его данные и удалить его.

### Планируемое затраченное время:
13 часов

**Comment by daniyarotegen** [comment]
неактуально, так как для фронтенда будут использованы джанговские представления
