### ISSUE TITLE
Создать функции вывода страниц для crud операций запросов на создание чата

### ISSUE THREAD

**Issue by AlibekBeket** [AttractorSchool/ESDP-AP-10-1#90]
### Для чего это нужно?
Для составление запроса на создание чата через сайт

### Как это сделать?
Зайти в папку webapp
Создать html файлы для crud запросов на создание чата
Создать в папку views файл для вывода страниц с crud операциями запросов на создание чата и прикрепить к ним html файлы
Написать js файлы для crud api запросов на создание чата
Указать url пути для этих страниц

### Критерии приема
Зайдя на сайт, смогу сформировать запрос на создание чата

### Планируемое затраченное время:
5 часов

**Comment by daniyarotegen** [comment]
неактуально, так как для фронтенда будут использованы джанговские представления
