### ISSUE TITLE
Сделать модель ролей и привилегий

### ISSUE THREAD

**Issue by AlibekBeket** [AttractorSchool/ESDP-AP-10-1#92]
### Для чего это нужно?
Для проверки и выдачи прав пользователю

### Как это сделать?
Зайти в папку accounts
Создать модель "привилегий"
В модели "роли" добавить поле многие ко многим к модели "привилегий"

### Дополнительные действия
Зарегистрировать модели в админке 

### Критерии приема
Через админку смогу создать привилегии и роли

### Планируемое затраченное время:
2 часов

**Comment by IvanAshikhin** [comment]
Соответствует критерию приемки
