### ISSUE TITLE
Доработать js файл для вывода новости в ленты

### ISSUE THREAD

**Issue by AlibekBeket** [AttractorSchool/ESDP-AP-10-1#93]
### Для чего это нужно?
Для правильного отображения новостной ленты

### Как это сделать?
Зайти в newsline.js и там добавить блок для отображения фотографий которые привязаны к новости
Добавить условия если фотографий несколько, чтоб было приятно глазу
Максимальное количество картинок 5

### Критерии приема
Зайдя на страницу новостной ленты, будут видны все фотография новости в аккуратном виде

### Планируемое затраченное время:
2 часа

**Comment by daniyarotegen** [comment]
неактуально, так как для фронтенда будут использованы джанговские представления
