### ISSUE TITLE
Переделать дизайн приложения в соответствии с утвержденным дизайном

### ISSUE THREAD

**Issue by ValentinKim531** [AttractorSchool/ESDP-AP-10-1#97]
**Для чего это нужно?**
Для последующих демонстраций приложения заказчику и организаторам проекта 

**План решения**
Очистить стили и написать новые (стили, в соответствии с утвержденным Заказчиком дизайном) для существующих страниц. 

** Дополнительные действия** 
Создать дополнительные страницы детального просмотра мероприятия, список резидентов.

**Критерии приемки**
Обновленный дизайн реализован для существующих страниц. 

**Планируемое время работы**
8 часов

**Фактически затраченное время**
16 часов

**Comment by nurlansapyzhan** [comment]
Фактически затраченное время 16 часов. Причина: Создание дополнительных страниц и реализация стилей с нуля
